### ISSUE TITLE
Якорь, на который указывает ссылка, отсутствует или указан у неподдерживаемого элемента

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-yandex-turbo-feed#45]
Здравствуйте, прошу прощение, за беспокойство. Пользуюсь вашим плагином для яндекс.турбо, плагин очень нравится, но возникла проблема с ссылками типа - якорь. Подскажите пожалуйста, возможно ли в будущем исправить данную ошибку, для примера выложил код страницы https://codeshare.io/5PJvxQ  Через отладчик в вебмастере показывает ошибку. "Якорь, на который указывает ссылка, отсутствует или указан у неподдерживаемого элемента. В качестве якоря можно использовать контент в виде аккордеона или заголовок h1–h6."  Заранее благодарю за ответ.

**Comment by alimuradov** [comment]
Проблема до сих пор актуальна. Исправьте пожалуйста)

**Comment by mihdan** [comment]
Проблема не в плагине, а контенте, который генерит сайт. По ссылке выше видно, что причина плагин TOC, который ставит ссылки, на которые матерится yandex

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-yandex-turbo-feed/commit/5682a200b78dd70f505a158632e84c4a7f913825

**Comment by trendion** [comment]
материться до сих пор
