### ISSUE TITLE
Несколько фидов

### ISSUE THREAD

**Issue by artikus11** [mihdan/mihdan-yandex-turbo-feed#5]
Как будет работать плагин если надо сделать два разных фида, с разными именами. Например для простых записей и кастомных?

**Comment by mihdan** [comment]
- [ ]  Отдельный post type для каждого фида
- [ ]  Настройки прилепить как метабокс поста
- [ ]  Перенести настройки старые в новые

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-yandex-turbo-feed/commit/fbf8978ba2107191eef7ab538f327616babfd964
