### ISSUE TITLE
Добавить возможность игнорировать more в контенте и выводить полный текст.

### ISSUE THREAD

**Issue by vjik** [mihdan/mihdan-yandex-turbo-feed#53]
Сабж.

**Comment by marta-me** [comment]
Плюсану. Очень жду. Спасибо заранее.

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-yandex-turbo-feed/commit/43bfa0ddf746efac3d3b615b09a999b4ee080bbf

@vjik, @marta-me, проверьте, пожалуйста
