### ISSUE TITLE
При выводе контента указывать тип фида.

### ISSUE THREAD

**Issue by vjik** [mihdan/mihdan-yandex-turbo-feed#54]
В функции `the_content_feed()` указать тип фида, чтобы можно было при использовании хуков из этой функции понимать, что это именно фид для яндекс.турбо.

**Comment by mihdan** [comment]
Добавил два фильтра:

- `mihdan_yandex_turbo_feed_item_excerpt` - для анонса
- `mihdan_yandex_turbo_feed_item_content` - для содержимого
