### ISSUE TITLE
Добавить возможность отключать вывод изображения записи.

### ISSUE THREAD

**Issue by vjik** [mihdan/mihdan-yandex-turbo-feed#56]
Сабж.

**Comment by mihdan** [comment]
Спасибо, готовлю блок с настройками и общими и теми, что можно в посте переопределить

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-yandex-turbo-feed/commit/5aea17a8a501dd9ab378bcb1cb9743da166a96e5
