### ISSUE TITLE
Получать контент из пользовательского поля

### ISSUE THREAD

**Issue by ali3412** [mihdan/mihdan-yandex-turbo-feed#57]
Для того, чтобы формировать контент отличный от основного, было бы удобно получать контент для турбо из другого поля. Так же это пригодилось бы для сайтов, сделанных на конструкторах. В частности, Elementor в основном содержании записи содержит нечитаемый для турбо контент.

**Comment by mihdan** [comment]
Используйте хук `mihdan_yandex_turbo_feed_item_content` - https://github.com/mihdan/mihdan-yandex-turbo-feed/blob/master/templates/feed.php#L50

**Comment by mihdan** [comment]
```php
<?php
add_filter(
    'mihdan_yandex_turbo_feed_item_content',
    function( $content, $post_id ) {
        return get_field( 'ваше поле acf, например', $post_id );
    },
    10,
    2
);
```
