### ISSUE TITLE
Добавить возможность управлять настройками записей через Bulk Edit

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-yandex-turbo-feed#61]
Все галочки, которые есть в постах внутри метабокса Yandex Turbo было бы неплохо править в режиме Bulk Edit.

Туториалы:

- https://rudrastyh.com/wordpress/bulk-edit.html
- https://burtnek.ru/wordpress/kak-dobavit-massovoe-redaktirovanie-postov-v-wordpress/
- https://wordpress.stackexchange.com/questions/365150/how-to-add-a-custom-field-to-quick-edit

**Comment by mihdan** [comment]
@karpalig можно тут следить

**Comment by karpalig** [comment]
**Не работает индикация**
1. Выключил ленту новой функцией (одной галкой) в настройках плагина
2. В коде ленты вижу <item turbo="false">
3. Но индикация все так же зелёная
![image](https://github.com/mihdan/mihdan-yandex-turbo-feed/assets/7493374/a7efe1ce-1635-44b5-bef1-3869ad5a90cb)

**Как отменить "удалить турбо-страницу"** удалённую через свойства записи:
1. Если у записи нажать свойства и нажать удалить появляется красный маркер.
2. Если зайти в свойства снова, то галки больше нет, получается её не отжать и получается не отменить действие "удалить турбо-страницу"
![image](https://github.com/mihdan/mihdan-yandex-turbo-feed/assets/7493374/d73d5229-2618-4fb5-8f5c-8cc2d58afade)
