### ISSUE TITLE
Совместная работа с плагином Lite Video Embed

### ISSUE THREAD

**Issue by leskei217** [mihdan/mihdan-yandex-turbo-feed#62]
У меня вопрос по видео-плагину в связке с Турбо-плагином.

Втыкаю видео через Гутенберг, а в Турбо-страницах - ошибка: вставляется только картинка, без ссылки на youtube.
Как подружить два плагина? - чтобы в Турбо нормально видос бы вставлялся?

**Comment by mihdan** [comment]
Исправлено в 1.6.5 https://github.com/mihdan/mihdan-yandex-turbo-feed/commit/61c5e67c8292e1d234ce5d2befd6bfff7f19d1ad
