### ISSUE TITLE
Добавить настройку для указания определенной рубрики

### ISSUE THREAD

**Issue by fdezign** [mihdan/mihdan-yandex-turbo-feed#8]
Есть настройка для таксономии, но еще бы ограничение по ID записи в таксономии

Например, рубрика Блог, определенный тег etc

**Comment by mihdan** [comment]
@fdezign можно прям пример на пальцах, чтобы я понял о чем речь, спасибо

**Comment by fdezign** [comment]
Доброго Спасибо за быструю реакцию Вот в аналогичном плагине от teplitsa https://www.screencast.com/t/9nBShnWUE9PJ Выбирается таксономия и ID в ней для фильтрации У меня это рубрика Блог   18.04.2018, 19:42, "Mikhail Kobzarev" <notifications@github.com>:@fdezign можно прям пример на пальцах, чтобы я понял о чем речь, спасибо—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.   --- С уважением,Пименов Дмитрий (Эрин)

**Comment by mihdan** [comment]
@fdezign теперь пончтно, добавим
